# Welcome to Jekyll!
#

# Site settings
title: KNIJFFIGHT
description: |
  zelfverdediging - kracht - condititie
owner: KNIJFFIGHT # or company name
# first_published: 2016 # if migrating another site, the year of your first publish
email: jef@knijffight.nl
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knijffight.nl" # the base hostname & protocol for your site
social:
  facebook-official: https://facebook.com/knijffight
  instagram: https://instagram.com/knijffight
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
